#!/bin/bash

#PBS -N SRR896564_Pan_genomeak_split_megablast
#PBS -q batch
#PBS -l nodes=1:ppn=12
#PBS -l walltime=100:00:00
#PBS -j oe

date
module load blast+
cd /opt/ncbi/databases

blastn -task megablast -db nt -evalue 1e-6 -num_descriptions 5 -num_alignments 5 -num_threads 12 -query /scratch/smpenni/SRR896564_Pan_genomeak.fasta -out /scratch/smpenni/SRR896564_Pan_genomeak_megablast.blast 
date
